In [6]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.employee_count += 1
        print(Employee.employee_count)

    def display_employee_details(self):
        print(f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}")

 
    def average_salary(employee_list):
        total_salary = sum(emp.salary for emp in employee_list)
        return total_salary / len(employee_list) if len(employee_list) > 0 else 0


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, hours_per_week):

        super().__init__(name, family, salary, department)
        self.hours_per_week = hours_per_week



employee1 = Employee("Dinesh", "Kyanam", 50000, "HR")
employee2 = Employee("Kishore", "Pathrapalli", 60000, "Finance")


fulltime_employee1 = FulltimeEmployee("Jagadeesh", "Gambling", 70000, "IT", 40)
fulltime_employee2 = FulltimeEmployee("Nikhil", "Kyanam", 80000, "Marketing", 35)
print("Employee Details:")
employee1.display_employee_details()
employee2.display_employee_details()
print("\nFulltime Employee Details:")
fulltime_employee1.display_employee_details()
fulltime_employee2.display_employee_details()
employee_list = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employee_list)
print(f"\nAverage Salary: {avg_salary}")

1
2
3
4
Employee Details:
Name: Dinesh, Family: Kyanam, Salary: 50000, Department: HR
Name: Kishore, Family: Pathrapalli, Salary: 60000, Department: Finance

Fulltime Employee Details:
Name: Jagadeesh, Family: Gambling, Salary: 70000, Department: IT
Name: Nikhil, Family: Kyanam, Salary: 80000, Department: Marketing

Average Salary: 65000.0


In [3]:
import numpy as np
random_vector = np.random.uniform(1, 20, 20)
reshaped_array = random_vector.reshape(4, 5)
print("Original Matrix:")
print(reshaped_array)
reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0
print("\nMatrix after replacing max in each row with 0:")
print(reshaped_array)

Original Matrix:
[[12.7779986  16.89145263 15.28166494  1.02165094  4.68486475]
 [11.44991746  8.85212188  4.2917247   3.90645297 18.85267334]
 [ 5.35693885 10.85398738 15.99482049  1.00645673  3.94225776]
 [19.01116024 16.00777724 13.65313989  4.23750544  7.76228123]]

Matrix after replacing max in each row with 0:
[[12.7779986   0.         15.28166494  1.02165094  4.68486475]
 [11.44991746  8.85212188  4.2917247   3.90645297  0.        ]
 [ 5.35693885 10.85398738  0.          1.00645673  3.94225776]
 [ 0.         16.00777724 13.65313989  4.23750544  7.76228123]]
